import type { Metadata } from "next";
import "../globals.css";
import Sidebar from "@/components/layout/Sidebar";
import DashboardHeader from "@/components/layout/DashboardHeader";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className="flex h-screen overflow-y-hidden">
      <Sidebar />
      <div className="flex-1 overflow-y-auto">
        <DashboardHeader />
        <div className="p-10 md:px-10 px-3">{children}</div>
      </div>
    </main>
  );
}
